### ISSUE TITLE
error datetime default

### ISSUE THREAD

**Issue by ddtddt** [mistic100/Piwigo-Guest-Book#7]
Hi :-)

in maintain.class.php

they're line55
`date` datetime NOT NULL DEFAULT now(),

the recent sql no acceop can you update with
`date` datetime NOT NULL DEFAULT "1970-01-01 00:00:00",

**Comment by mistic100** [comment]
NOW() is well supported

**Comment by plegall** [comment]
> NOW() is well supported

I give a detail: since MySQL 5.6 (which is OK on most of servers nowadays)
